/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chikul.glb -o src/components/Chikul.jsx -k -K -r public 
Author: rreweerrewee@gmail.com (https://sketchfab.com/jerryzilla)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chiku-fart-girl-ea804049bd734abc92878fe1869709c4
Title: Chiku fart girl
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Chikul({
  animation="mixamo.com",
  ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/chikul.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

    useEffect(() => {
      // console.log('Loaded Materials:', materials);
      actions[animation]?.reset().fadeIn(0.24).play();
      return () => actions?.[animation]?.fadeOut(0.24);
    }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.032}>
          <group name="05965dadd7a54c699821d015ce94c07efbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Chiku_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_9">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_141" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_144" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.Chiku} skeleton={nodes.Object_142.skeleton} />
                    <skinnedMesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.ChikuProps} skeleton={nodes.Object_143.skeleton} />
                    <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.Chiku} skeleton={nodes.Object_145.skeleton} />
                    <skinnedMesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.ChikuGlows} skeleton={nodes.Object_146.skeleton} />
                    <skinnedMesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.ChikuClothes} skeleton={nodes.Object_147.skeleton} />
                    <skinnedMesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.ChikuBlush} skeleton={nodes.Object_148.skeleton} />
                  </group>
                </group>
                <group name="Pizza_Box_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Pizza_Box" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Pizza_Slice_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Pizza_Slice" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Chiku_Apron" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Chiku" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/chikul.glb')
