/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Globe.glb -o src/components/Globe.jsx -k -K -r public 
Author: rreweerrewee@gmail.com (https://sketchfab.com/jerryzilla)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chiku-fart-girl-sitting-on-the-earth-df91764c24d443fbad3dca432afa04af
Title: Chiku fart girl sitting on the Earth
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Globe({
  animation,
  ...props}) {
     const group = React.useRef()
  const { nodes, materials } = useGLTF('/models/Globe.glb')
    //  useEffect(() => {
    //     // console.log('Loaded Materials:', materials);
    //     actions[animation]?.reset().fadeIn(0.24).play();
    //     return () => actions?.[animation]?.fadeOut(0.24);
    //   }, [animation]);

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Nuevo_Proyectoobjcleanermaterialmergergles">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.Earth} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Material} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Material_1} />
            <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Material_2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Globe.glb')
