/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/momoi.glb -o src/components/Momoi.jsx -k -K -r public 
Author: Game Extractor (https://sketchfab.com/GameExtractor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/momoi-sea-salt-summer-farlight-84-characters-5b2eada6a269441cade8ddbdb67d044a
Title: Momoi Sea-Salt Summer | Farlight 84 Characters
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Momoi({
  animation="Avatar_HOD_UR_Set02_LodP|HOD_UR_Set02_IdleShow.003",
  ...props

}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/momoi.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)


    useEffect(() => {
      // console.log('Loaded Materials:', materials);
      actions[animation]?.reset().fadeIn(0.24).play();
      return () => actions?.[animation]?.fadeOut(0.24);
    }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.012}>
          <group name="08379eb0c26d47c19b176fb05b170601fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Avatar_HOD_UR_Set02_LodP" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_355" />
                    <skinnedMesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.MI_HOD_UR_Set02_Hair} skeleton={nodes.Object_356.skeleton} />
                    <skinnedMesh name="Object_357" geometry={nodes.Object_357.geometry} material={materials.MI_HOD_UR_Set02_EL} skeleton={nodes.Object_357.skeleton} />
                    <skinnedMesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials.MI_HOD_UR_Set02_ELGlass} skeleton={nodes.Object_358.skeleton} />
                    <skinnedMesh name="Object_359" geometry={nodes.Object_359.geometry} material={materials.MI_HOD_UR_Set02_Skin} skeleton={nodes.Object_359.skeleton} />
                  </group>
                </group>
                <group name="Avatar_HOD_UR_Set02_LodP001" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/momoi.glb')
